version: '3'
services:
  #　メタデータ保存用Mysql
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./files/hiveddls:/docker-entrypoint-initdb.d
      - ./files/share/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_DATABASE: metastore
      MYSQL_ROOT_PASSWORD: root
    container_name: pyspak_sample_db2
    networks:
      - app-net-big
  # ワーキングコンテナ
  workspace:
    build: ./files
    command: sleep infinity
    depends_on:
      - mysql
    container_name: pyspak_sample_db
    networks:
      - app-net-big


networks:
  app-net-big:
    driver: bridge